---
- name: Bootstrap OpenBSD
  block:
    - name: Install Python
      ansible.builtin.raw: pkg_add python%3.8
  become: true
#        update_cache: yes
#        upgrade: dist
#        autoremove: yes
#        autoclean: yes
#    - name: Check if reboot required
#      stat:
#        path: /var/run/reboot-required
#      register: reboot_required
#    - name: Reboot if required
#      reboot:
#        reboot_timeout: 600
#      when: reboot_required.stat.exists
